import React from 'react'

const LaFrance = () => {
    return (
        <section className="container mx-auto pt-10 pb-40 text-lg">
            <div className="m-auto">
                <h1 className="sub-heading text-primary mb-6">
                    CONDITIONS GENERALES
                </h1>
                <ol className='list-decimal flex flex-col gap-4 list-inside text-lg mt-4' start={1}>
                    <li> Les termes de ce Contrat précisent l’accord entre le Propriétaire de l’Animal (« vous », « votre») et le Vétérinaire (« nous », « notre ») dont les coordonnées figurent au recto des présentes, pour la fourniture par le Vétérinaire des services stipulés dans la documentation du Plan de prévention pour animal de compagnie – VetoPlan (les «Services ») dont nous vous avons remis une copie. Dans l’éventualité où les termes de ce Contrat seraient en conflit avec ceux spécifiés dans nos conditions générales ou particulières de services, les termes spécifiés dans ce Contrat prévaudront. De même, si les termes figurant au recto du présent Contrat diffèrent des termes figurant sur cette page, alors les termes au recto prévaudront.</li>
                    <li>Vous devez vérifier les termes de ce Contrat en détail avant de vous engager. Si vous pensez qu’il y a des erreurs dans ce Contrat ou si vous avez des questions au sujet du Contrat, vous devez nous contacter immédiatement. Une fois que vous signez le Contrat, vous serez lié par ses termes.</li>
                    <li> Nous n’avons aucune obligation de conclure le Contrat avec vous et tout Contrat signé par vos soins et nous ayant été remis sera considéré comme une offre de votre part afin de commencer votre adhésion à la date indiquée au recto. Votre offre sera considérée comme acceptée à la première en date des actions suivantes : soit lorsque nous vous fournirons une copie du contrat signé par nos soins, soit lorsque nous prélèverons la première mensualité. A ce moment, le Contrat aura force obligatoire entre vous et nous.</li>
                    <li>Dans le cas où votre Contrat aurait été conclu à distance ou hors établissement tel que défini à l’Article L.121-16 du Code de la consommation, vous disposez d’une période de 14 jours calendaires à partir de la date à laquelle vous nous avez envoyé le Contrat signé, pour vous rétracter et annuler le Contrat en nous notifiant votre souhait au moyen d’une déclaration dénuée d’ambiguïté par exemple en nous renvoyant à notre nom et à notre adresse tels qu’ils figurent sur le Contrat un courrier selon le modèle figurant ci-dessous :</li>




                    <li>Le présent Contrat est valable uniquement dans la (les) clinique(s) mentionnée(s) au recto et ne s’applique que pendant les horaires d’ouverture de cette/ces clinique(s).</li>
                    <li>Il est à durée déterminée trimestrielle. Les produits et les services dispensés au titre de ce Contrat vous seront proposés selon un calendrier établi lors de votre adhésion, selon un cycle trimestriel. Cette périodicité des prestations, par trimestre, vous permettra de bénéficier des produits et des services adaptés qui figurent dans les conditions particulières de ce Contrat qui s’appliquent aux soins de votre animal, et qui sont annexées à ce Contrat. Nous vous précisons que la valeur totale des produits et services qui vous seront proposés ne pourra excéder 199 € par trimestre.</li>
                    <li>Votre Contrat sera renouvelé automatiquement par tacite reconduction à la fin de chaque période de trois mois, pour une autre période de trois mois. Vous pouvez notifier la résiliation du contrat pour quelque raison que ce soit et sans frais en nous faisant parvenir un avis de résiliation par lettre recommandée avec A.R. au moins 20 jours avant la fin de ladite période. La résiliation prendra effet à la fin de la période trimestrielle en cours.</li>
                    <li>Vous pouvez également résilier le Contrat à tout moment (a) si vous changez de Vétérinaire, (b) si votre animal venait à décéder, ou (c) suite à la survenance de tout autre évènement de force majeure au sens de l’article 1218 du Code Civil, ou autre motif légitime, qui empêcherait l’exécution par vous du Contrat. Dans ces conditions, la résiliation du Contrat prendra effet 20 jours après réception de votre demande de résiliation adressée par lettre recommandée avec A.R..</li>
                    <li>Si au moment de votre résiliation effective du Contrat vous avez bénéficié de prestations pendant le cycle trimestriel en cours pour lesquelles vous n’avez pas encore effectué de paiement, vous consentez à être prélevé de la valeur de ces prestations impayées, conformément au barème tarifaire Veto Plan figurant aux conditions particulières de votre Contrat.</li>
                    <li>Les Services ne seront fournis et le Plan de prévention pour animal de compagnie (le « Plan ») ne s’appliquera, qu’à l’animal (aux animaux) spécifiquement indiqué(s) au recto.</li>
                    <li>Nous fournirons pendant la durée du Contrat les Services conformément aux standards normaux de soins vétérinaires. Toutefois, nous ne pouvons vous fournir les Services qu’en fonction des rendez-vous que vous prendrez et il va de votre responsabilité de vous assurer que vous et l’animal (les animaux) couvert(s) par le Plan vous rendiez au cabinet vétérinaire pour les bilans de santé prévus par le Plan. Nous ne pouvons également fournir les Services que sur la base des informations que nous détenons concernant cet animal (ces animaux) et vous devez nous faire connaître toute information pertinente au sujet de votre animal (vos animaux) couverts y compris des détails précis concernant son (leur) état de santé général et de bien-être.</li>
                    <li>Les mensualités que vous devez honorer sont stipulées au recto. Certains vétérinaires ont mis en place un système de paiement en plusieurs fois auprès d’un tiers prestataire de paiement. Les conditions générales de ces prestataires seront applicables et vous serez invité à accepter leurs conditions générales avant le paiement. Le cas échéant, ces mensualités prendront en compte les remises visées pour tout animal supplémentaire à condition que le montant dû pour tout animal supplémentaire soit payé en vertu de la même instruction de paiement, c’est-à-dire lors du même prélèvement automatique.</li>
                    <li>Les mensualités seront prélevées par nous ou pour notre compte par l’agent que nous nommerons pour le prélèvement automatique conformément aux instructions de prélèvement automatique stipulées au recto. Les prélèvements automatiques seront effectués mensuellement à tout moment suivant la date à laquelle vous avec signé le Contrat (habituellement vers le 2ème ou le 16ème jour de chaque mois) jusqu’à ce que ce Contrat expire ou soit résilié pour une raison quelconque. Vous devez vous assurer que les informations fournies dans les instructions de prélèvement automatique sont correctes et nous informer de tous changements dans le futur. Vous devez aussi vous assurer que votre compte bancaire dispose des fonds suffisants pour le paiement par prélèvement automatique.</li>
                    <li>Les mensualités stipulées au recto incluent la TVA et toutes autres taxes dues. Toutefois, le taux de TVA est susceptible de changer et nous nous réservons donc le droit d’augmenter les mensualités afin de prendre en compte les augmentations du taux de TVA après vous en avoir informé.</li>
                    <li>Le coût de la fourniture des soins vétérinaires peut varier dans le temps à cause, par exemple, des variations du prix d’achat des vaccins et des médicaments. Nous nous réservons le droit de modifier le montant des mensualités et plus généralement les termes du présent Contrat à chaque période de reconduction tacite du Contrat. Vous serez averti de la modification des mensualités ou des modifications des termes du Contrat dans le courrier ou l’e-mail que nous vous adresserons au moins quarante (40) jours avant la date de reconduction du Contrat vous permettant ainsi de vous opposer à la reconduction dans les conditions visées à la clause 7 ci-dessus. Dans l’hypothèse où la lettre ou l’email relatif à la tacite reconduction ne vous serait pas envoyé conformément aux termes des présentes et où le montant des mensualités serait modifié ou des modifications importantes du Contrat seraient prévues, vous pourrez résilier immédiatement et à tout moment par écrit le Contrat. Dans ce cas, la résiliation prendra effet vingt (20) jours après la réception de votre courrier de résiliation et nous vous rembourserons toutes les sommes que vous nous auriez déjà réglées moins les frais des soins dispensés à votre (vos) animal (animaux) domestique(s) à cette date et tous les frais administratifs raisonnables que nous aurions engagés. Vous restez redevable de toutes les sommes dues relatives aux services ou aux biens que nous vous aurions déjà fournis jusqu’à la date de la résiliation effective. </li>
                    <li>Les prélèvements automatiques peuvent parfois être rejetés par votre banque ou organisme bancaire. Lorsque cela se produit et que nous (ou l’agent que nous nommerons) sommes dans l’incapacité de prélever votre mensualité, nous (ou notre agent) nous réservons le droit de vous facturer une pénalité d’un montant de — € par prélèvement rejeté au titre des frais générés, ainsi qu’après une mise en demeure d’y remédier dans un délai de 30 jours non suivie d’effet, des intérêts au taux de de trois fois le taux d’intérêt légal ainsi et/ou de suspendre la fourniture de Services et/ou de résilier ce Contrat jusqu’à ce que tous les arriérés y compris les pénalités et intérêts éventuels aient été payés. Tout prélèvement automatique impayé doit être considéré comme une dette à nous payer et, sans préjudice de nos droits, nous pourrons initier une procédure en recouvrement et une action en justice pour recouvrer la dette que vous nous devez.</li>
                    <li>. Nous pourrons résilier le Contrat immédiatement moyennant notification écrite dans les cas suivants :</li>
                    <li>(i) nous sommes dans l’incapacité d’effectuer les prélèvements automatiques sur votre compte à plus de deux reprises et/ou si vous ne réglez pas les arriérés de paiement dans les 30 jours suivant la date prévue pour le prélèvement automatique;</li>
                    <li> (ii) vous violez les termes de ce Contrat d’une autre façon substantielle et vous n’y remédiez pas dans un délai de 30 jours à compter de notre demande écrite d’y remédier; </li>
                    <li>(iii) vous faites l’objet d’une procédure de surendettement ou plus généralement vous êtes réputé incapable de payer vos dettes à leur échéance.</li>
                    <p>Dans l’hypothèse où nous résilions le Contrat sur le fondement de cette clause, vous devez, dans les 30 jours suivant la date de résiliation, nous régler une indemnité de résiliation équivalente aux prélèvements automatiques qui auraient été dus pour la durée du Contrat restant à courir. Vous acceptez que cette indemnité représente une pré-estimation sincère de nos pertes découlant d’une telle résiliation. Dans l’hypothèse où ce Contrat serait résilié conformément à cette clause, vous seriez dans l’obligation de régler des frais d’annulation de 15 euros payables à notre agent effectuant le prélèvement automatique afin de tenir compte de son temps et ses coûts dans l’annulation du prélèvement automatique.</p>
                    <li>Lorsque le prélèvement automatique est effectué par un tiers pour notre compte, vous acceptez et reconnaissez que le tiers n’est pas responsable de la fourniture des Services qui nous incombe et vous acceptez de ne pas porter de réclamations de quelque nature que ce soit auprès de ce tiers en raison de la fourniture des Services.</li>
                    <li>Il est possible que nous ne soyons pas en mesure de fournir les Services pour des motifs extérieurs à notre volonté. De telles circonstances incluent (mais ne sont pas limitées à l’absence ou la maladie du personnel vétérinaire qualifié et/ou lorsque nous sommes confrontés à une pénurie dans la fourniture des vaccins ou des médicaments. Lorsque nous accuserons du retard dans la fourniture des Services pour des motifs extérieurs à notre volonté, nous ferons ce que nous pourrons raisonnablement faire afin de réduire les délais et de trouver pour vous et votre animal domestique un autre rendez-vous. Toutefois, nous ne serons pas responsables si nous ne réussissons pas à vous fournir les Services dans ces circonstances.</li>
                    <li>Nous nous réservons le droit de transférer nos droits en vertu de ce Contrat à toute autre personne appropriée sous réserve que nous vous en informions mais ce Contrat est personnel, pour vous et votre animal domestique visé au recto, Vous ne pouvez transférer les bénéfices de ce Contrat à une autre personne ou modifier les animaux domestiques sur lesquels ce Contrat porte sans notre accord écrit.</li>
                    <li>Tous droits de propriété intellectuelle (y compris non limitativement les droits d’auteur, marques, noms commerciaux, fonds de commerce, droits sur les dessins, les droits de base de données, et les droits d’utiliser et de protéger la confidentialité des informations) découlant de ou en relation avec les Services sont notre propriété ou celle de nos concédants de licence.</li>
                    <li> A part vous, nous et le tiers nommé par nous aux fins de gérer le Plan et les prélèvements automatiques en notre nom, nul ne peut tirer un avantage quelconque des termes de ce Contrat.</li>
                    <li>Si pendant la durée du présent Contrat nous ne faisons pas appliquer nos droits à votre encontre, ou si nous tardons à le faire, cela ne signifiera pas que nous ayons renoncé à nos droits à votre encontre ni que vous n’ayez pas d’obligations à respecter.</li>
                    <li>Toutes les notifications faites sur le fondement du présent Contrat devront être faites par écrit et envoyées par lettre recommandée avec accusé de réception à la dernière adresse connue de la partie concernée, si ce n’est celle relative à la reconduction du Contrat qui pourra être faite par courrier simple ou mail à l’adresse/adresse mail que vous avez communiquées lors de votre souscription.</li>
                    <li>Nous conserverons et traiterons vos données personnelles conformément aux lois applicables sur la protection des données et la vie privée, y compris le Règlement (UE)2016/679 (le “RGPD”). Nous avons choisi Premier Vet Alliance Limited («PVA») pour administrer les règlements mensuels par prélèvement automatique du Plan de prévention pour animaux de compagnie que vous avez souscrit. Afin que PVA puisse mener à bien ces activités, nous collectons (pour le compte de PVA) les données personnelles et financières que vous nous fournissez dans le cadre du présent Contrat et nous communiquons ensuite ces informations à PVA (nom, adresse, numéro de compte et banque, adresse mail). Veuillez consulter la politique de confidentialité de PVA présentée ci-dessous expliquant les traitements opérés par PVA sur vos données. Nous ne traiterons que celles de vos données personnelles et des informations financières que vous nous fournirez dans le présent Contrat qui sont nécessaires pour la gestion et la fourniture par nous des Services, y compris par la communication de ces données à PVA pour la fourniture des prestations de services qui lui incombe, y compris à des fins de marketing si vous l’avez autorisé (nom, adresse électronique, numéros de téléphone mobile et nom des animaux de compagnie concernés). Dans ce cadre, il pourra être nécessaire que nous communiquions vos coordonnées à nos agents, employés, sociétés du groupe et autres prestataires de services. Les données personnelles que vous nous aurez communiquées dans le cadre du présent Contrat seront conservées pour la durée du Contrat, augmentée de la durée nécessaire au respect de nos exigences légales. Vous disposerez d’un droit d’accès, de rectification et de suppression de vos données personnelles en nous écrivant à l’adresse figurant au recto de ce Contrat.</li>
                    <li>Si un tribunal ou toute autre autorité compétente décidait que l’une quelconque des clauses de ce Contrat est nulle, non écrite, illégale ou inapplicable, la clause sera seulement exclue du reste des clauses de ce Contrat, qui continuera à produire ses effets dans toute la mesure autorisée par la loi.</li>
                    <li>Ce Contrat est soumis à la loi française et à la compétence exclusive des tribunaux français. Toutefois, en cas de différend, vous avez en qualité de consommateur, la possibilité avant toute action en justice de recourir à la procédure de médiation prévue aux articles L. 616-1 et suivants du Code de la Consommation. Les coordonnées du médiateur de la consommation de la profession de vétérinaire sont les suivantes : Médiateur de la consommation de la profession de vétérinaire – Conseil National de l’Ordre des vétérinaires – 34 rue Bréguet – 75011 Paris. Vous pouvez également remplir un formulaire en ligne accessible à https://www.veterinaire.fr en l’adressant à l’adresse électronique mediateur-conso@ordre.veterinaire.fr.</li>
                    <p>POLITIQUE DE CONFIDENTIALITE DE PREMIER VET ALLIANCE LIMITED
                    </p>
                    <p>Premier Vet Alliance Limited (numéro d’entreprise 07267818) («PVA») est l’administrateur de votre Plan de soins pour animaux de compagnie (le «Plan») et collecte vos règlements mensuels par prélèvement automatique pour le compte de votre vétérinaire.</p>
                    <p>PVA prend la protection de vos données personnelles extrêmement au sérieux. Cette politique de confidentialité définit la base sur laquelle les données collectées par PVA à votre sujet ou que vous fournissez indirectement à PVA, seront traitées par PVA.</p>
                    <p>PVA traitera les données personnelles et les informations financières fournies par vous dans le cadre de ce Contrat, et fournies à PVA par votre vétérinaire, et toutes les mises à jour de ces informations fournies par votre vétérinaire dans la mise en œuvre du Plan (“vos Données Personnelles“) conformément aux lois applicables en matière de protection des données y compris le règlement (UE)2016/679 (le «RGPD»).</p>
                    <p>PVA utilisera vos données personnelles dans le but d’administrer le Plan, y compris la collecte des prélèvements pour le compte de votre vétérinaire. PVA partagera également une quantité limitée et pseudonymisée de vos Données Personnelles avec la société CACI Limited à des fins d’analyse pour que PVA puisse améliorer les produits et services qu’elle offre. PVA pourra également transférer vos Données Personnelles conformément au processus de modification globale des données SEPA afin que le destinataire puisse assumer la responsabilité de la collecte ou de l’administration des prélèvements pour le compte de votre vétérinaire. Cette utilisation par PVA de vos Données Personnelles est justifiée par le fait que, en tant qu’administrateur du Plan, PVA a une nécessité commerciale d’utiliser vos Données Personnelles à ces fins.</p>
                    <p>Si vous cochez la case à cet effet sur le recto de votre Contrat, vous autorisez PVA à utiliser vos Données Personnelles afin de vous fournir pour le compte de votre vétérinaire des informations sur les Services qui pourraient vous intéresser. Le fondement légal d’une telle utilisation est que vous avez donné votre consentement à l’utilisation de vos Données Personnelles à des fins de marketing. À tout moment, vous pourrez demander à PVA de cesser cette utilisation à des fins de marketing et retirer l’accord que vous avez donné pour l’utilisation de vos Données Personnelles à cette fin en écrivant à l’adresse visée ci-dessous et/ou à votre vétérinaire.</p>
                    <p>PVA conservera vos Données Personnelles aussi longtemps que cela est nécessaire pour se conformer aux objectifs énoncés dans cette politique de confidentialité. Si vous avez demandé à PVA d’arrêter d’utiliser vos Données Personnelles à des fins de marketing, votre nom et toutes les informations y rattachées seront conservées sur une liste de suppression pour s’assurer que PVA ne vous envoie plus de communications marketing à l’avenir.</p>
                    <p>Lorsque cela est pertinent aux fins décrites dans cette politique de confidentialité, PVA pourra partager vos Données Personnelles avec des tiers qui interviennent dans l’exécution du Plan, y compris en ce qui concerne la collecte ou l’administration des prélèvements (par exemple l’éditeur de logiciels), les fournisseurs de services tiers de PVA (tels que le partenaire de développement et l’hébergeur de PVA), les tiers qui gèrent le marketing direct de PVA et les intervenants tiers sélectionnés dans le cadre de toute vente, cession ou cession des activités de PVA. Cependant, PVA ne transfèrera pas vos Données Personnelles en dehors de l’EEE (où vous résidez dans l’EEE).</p>
                    <p>Vous pourrez : (a) accéder aux informations que PVA détient sur vous, et savoir dans quel but PVA utilise ces informations; (b) corriger les inexactitudes dans les informations que PVA détient à votre sujet; et (c) dans certaines circonstances: (i) demander à PVA d’effacer les informations qu’il détient sur vous; (ii) recevoir une copie de tout renseignement personnel fourni à PVA par vous directement ou indirectement et demander à PVA de fournir cette information à un tiers; (iii) restreindre l’utilisation de vos Données Personnelles par PVA; et (iv) vous opposer à l’utilisation de vos Données Personnelles par PVA, y compris lorsque ces informations sont utilisées à des fins de marketing direct. Vous pouvez exercer l’un de ces droits en écrivant à PVA à l’adresse indiquée à la fin de ce document.</p>
                    <p>Vous avez le droit de vous plaindre auprès de l’autorité de surveillance compétente de toute juridiction compétente au sujet de l’utilisation de vos Données Personnelles par PVA, et notamment la Commission Nationale de l’Informatique et des Libertés (CNIL), l’autorité compétente pour la France.</p>
                    <p>Si vous souhaitez contacter PVA à propos de l’utilisation de vos Données Personnelles, veuillez écrire au Délégué à la Protection des Données Personnelles (DPO), Premier Vet Alliance Limited, New Bond House, Bond Street, Bristol, BS29AG, Royaume- Uni.</p>
                </ol>
            </div>
        </section>
    )
}

export default LaFrance
