export default function RepublicOfIreland() {
    return (
        <section className="container mx-auto pt-10 pb-40 text-lg">
            <div className="m-auto">
                <h1 className="sub-heading text-primary mb-6">
                    Republic of Ireland T&Cs
                </h1>
                <ol className='list-decimal flex flex-col gap-4 list-inside text-lg mt-4' start={1}>
                    <li> The terms of this Agreement set out the agreement between the Pet Owner (“you”, “your”) and the Veterinary Surgeon (“we”, “us”, “our”) for the supply to you of the services set out in our Pet Care Plan promotional literature, copies of which have been provided by us to you (Services). The provision of such Services shall also be subject to our standard terms & conditions for goods and services provided by us. This agreement is only valid for visits in the aforementioned clinic and only applicable to normal working hours.</li>
                    <li>You should check the terms of this Agreement in detail before committing yourself to its terms. If you think there is any mistake in this Agreement or if you have any questions about it then you should contact us straight away. Once you sign the Agreement you will be bound by its terms.</li>
                    <li> If the terms overleaf differ from the terms on this page then the terms overleaf will prevail. This is to ensure that the terms written on the front sheet of the Agreement take precedence. Our Pet Care Plan is designed to help you spread your vet costs in respect of the Services over a 12 month period by making monthly in advance payments to us.</li>
                    <li>Because your costs for the Services are spread over 12 months, this is a fixed-term 12 month Agreement and you can’t end the Agreement or stop paying the monthly payments other than at the end of a 12 month period in accordance with clause 7.</li>
                    <li>You can terminate this Agreement by giving us written notice of your intention to do so at least 60 days prior to the anniversary of the Agreement by registered post, in which case the Agreement will end at the end of that 12 month period.</li>
                    <li>Unless you give us notice that you don’t want to renew your Agreement as set out in clause 7 above, your Agreement will renew automatically at the end of each 12 month period for another 12 months. We are under no obligation to enter into the Agreement with you and any Agreement signed by you and delivered to us shall be considered an order by you to commence your membership on the date set out overleaf. Your order will be deemed to be accepted when we issue you with a copy of the Agreement signed by us or we take the first monthly Direct Debit payment whichever is the earlier. At this time the Agreement will become binding on you and us.</li>
                    <li>You have a period of 14 days from the date on which you deliver the signed Agreement to us to withdraw your order and cancel the Agreement by notifying us that you wish to cancel. Where you do this, we shall refund to you any amounts which you have paid to us less the cost of treating your pet(s) as at that date and any administrative costs reasonably incurred by us. You shall remain liable to pay any sums due in respect of goods or services we have already supplied to you.</li>
                    <li>The Services will only be provided and the Plan shall only apply in respect of the specific pet(s) named overleaf.</li>
                    <li>The Services will at all times be provided by us in accordance with the normal standards of veterinary care. However, we can only provide the Services pursuant to appointments which you make and it is your responsibility to make sure that you and the pet(s) covered by the Plan attend our surgery for checkups in accordance with the Plan. We can also only provide the Services on the basis of the information which we have about your pet(s) and you must let us know about all relevant information concerning your pet(s) including accurate details of their general health and wellbeing.</li>
                    <li>The monthly payments which you are required to make to us are set out overleaf and if applicable these monthly payments will take into account the additional pet discounts referred to provided that any additional pet(s) is/are paid for under the same Direct Debit instruction.</li>
                    <li>The monthly payments will be collected by us or on our behalf by our nominated agent by Direct Debit in accordance with the Direct Debit instruction set out overleaf. The monthly payments will be collected monthly at any time following the date you sign the Agreement (usually on or around the 2nd day of each month) until such time as this Agreement expires or is terminated for whatever reason. You must ensure that the details you provide in the Direct Debit instruction are correct and inform of us any changes in the future. You are responsible for ensuring that sufficient funds are in your account for the Direct Debit payments.</li>
                    <li>The monthly payments set out overleaf are inclusive of VAT and all other relevant taxes. VAT rates are liable to change however and so we reserve the right to increase the monthly payments to take account of increases in VAT rates on notice to you.</li>
                    <li>The cost of supplying veterinary treatment can vary from time to time due to for instance fluctuations due to the cost of vaccinations drugs. We therefore reserve the right to vary the monthly payments provided that we give you 14 days’ prior notice of any increase to the monthly payments.</li>
                    <li>There are instances in which Direct Debit collections may be rejected by your relevant bank or building society. Where this happens and we (or our nominated agent) are unable to collect a monthly payment from you, we reserve the right to charge interest to you at the rate of 4% above the base rate of the European Central Bank and/or suspend the provision of Services and/or cancel this Agreement until such time as all arrears have been cleared. Any unpaid direct debit collections shall be treated as a debt payable by you to us and, without prejudice to our other rights, we may take debt recovery and legal action to recover debts from you.</li>
                    <li>We may terminate this Agreement immediately on notice in the following circumstances: (i) we are unable to collect Direct Debits from you on more than 2 occasions and/or you fail to settle overdue payments within 30 days of the scheduled Direct Debit collection date; or (ii) you breach the terms of this Agreement in any other material way and do not remedy such breach within 30 days of us requiring you to do so by notice in writing; or (iii) you are declared bankrupt or otherwise deemed to be unable to pay your debts as they fall due. In the event that we terminate the Agreement pursuant to this clause, you must, within 30 days of the date of termination, pay us a termination fee equivalent to the Direct Debit payments that would have been due for the remainder of the 12-month term. You agree that this payment represents a genuine pre-estimate of our losses arising from such termination. In the event that this Agreement is terminated early (regardless of the reason), you shall be liable to pay a €15 cancellation charge, which is payable to our Direct Debit agent to reflect their time and cost in cancelling the direct debit. </li>
                    <li>Where the Direct Debit is collected by a third party on our behalf you agree and acknowledge that the third party is not liable for the provision of the Services by us and you agree not to bring any claim of whatsoever nature against the third party. </li>
                    <li>There may be instances where we are unable to provide the Services for reasons beyond our reasonable control. Such circumstances include (but aren’t limited to) the absence or illness of suitably qualified veterinary staff and/or where we have a shortage in the supply of necessary vaccinations or drugs. Where we experience delays in the provision of the Services to you for reasons beyond our control, we will do what we reasonably can to minimise these delays and accommodate you and your pet with another appointment. However, we will not be liable to you for a failure to deliver the Services in these circumstances.</li>
                    <li>We reserve the right to transfer our rights under this Agreement to any other suitable person provided that we give notice to you but this Agreement is personal to you and the pet(s) named overleaf. You cannot transfer the benefit of the Agreement to any person or transfer the pet(s) to which the Agreement relates without our prior written consent. </li>
                    <li> All intellectual property rights (including but not limited to copyright, trade marks, business names, goodwill, rights in designs, database rights, and the rights to use and protect confidential information) in or arising out of or in connection with the Services shall be owned by us or our third party licensors. </li>
                    <li> Except in respect of death or personal injury caused by our negligence, fraud or fraudulent misrepresentation, or any other matter for which it is unlawful to limit or exclude liability, our liability to you under this Agreement, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, shall be limited to [the monthly fees paid by you pursuant to this Agreement when the liability arises]. We shall have no liability to you in respect of any indirect or consequential losses arising under or in connection with this Agreement.</li>
                    <li>Except for you, us and any third party appointed by us for the purpose of administering the scheme and collecting Direct Debits on our behalf, no person may derive any benefit from the terms of this Agreement.</li>
                    <li>If at any time during this Agreement we decide not to enforce our rights against you, or if we delay in doing so, that will not mean we have waived our rights against you and will not mean that you do not have to comply with those obligations.</li>
                    <li>All notices given under the provisions of this Agreement must be in writing and sent to the last known address of the other party by registered post.</li>
                    <li>Premier Vets Alliance Limited shall be the data controller of your personal data and shall store and process your data in accordance with the privacy notice below.We will hold and process your personal data as a data processor in accordance with the principles of the EU Data Protection Directive 95/46/EC as implemented by the appropriate national law(s) and shall only do so for the performance of the Services. In the course of the provision of the Services it may be necessary to provide your details to our agents, employees, group companies and other service providers and you hereby give us your authority for us to do so.</li>
                    <li>If any court or other competent authority decides that any of the provisions of this Agreement is or are invalid, unlawful or unenforceable to any extent, the term(s) will, to that extent only be severed from the remaining terms of this Agreement which will continue to operate to the fullest extent operated by law.</li>
                    <li>This Agreement is subject to the laws of Ireland and you and we both agree to submit to the non-exclusive jurisdiction of the Irish courts. </li>
                    <li>Offers and discounts included in the Plan cannot be combined with other discounts. PRIVACY POLICY The administrator of the Direct Debits for the Pet Care Plan is Premier Vet Alliance Limited. The Premier Vet Alliance Limited takes your privacy and the protection of your personal data extremely seriously. All of your personal details and financial information will be processed by the Premier Vet Alliance Limited in accordance with the UK Data Protection Act 1998. Premier Vet Alliance Limited will use your personal data for the purposes of administering the Plan and this will include the processing of data which it receives from your veterinary surgery in connection with the Plan. Unless you request otherwise, in addition to using your personal data for the purposes of administering the Plan, the Premier Vet Alliance Limited may also use your personal data for the purposes of providing you with certain marketing information in relation to other products and services which it is able to offer to you and which it considers may be of interest to you. You have a right to require the Premier Vet Alliance Limited to stop using your personal information for any additional marketing reasons and if you would like the Premier Vet Alliance Limited to stop using your information or you have any questions about the personal information which Premier Vet Alliance Ltd The Quorum, Bond Street Bristol, BS1 3AE United Kingdom.</li>
                </ol>
            </div>
        </section>
    );
}
